const fs = require('fs');

const appCode = `import React, { useState, useEffect, useCallback, useRef } from 'react';
import { StyleSheet, View, Text, TouchableOpacity, SafeAreaView, Modal, ScrollView, Dimensions, StatusBar, Animated, Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';

const COLS=6,ROWS=4,TOTAL=ROWS*COLS,INITIAL_SEEDS=2;
const IDX={P2_DEF:0,P2_ATK:1,P1_ATK:2,P1_DEF:3};
const THEMES={savanna:{name:'Savana',primary:'#D97706',secondary:'#92400E',accent:'#FCD34D',bg:['#1C0F05','#2D1810'],boardBg:'rgba(139,69,19,0.3)',cellBg:'rgba(101,67,33,0.6)',cellBorder:'rgba(217,119,6,0.5)',seed:'#F59E0B',text:'#FEF3C7',emoji:'🌾'},sunset:{name:'Por do Sol',primary:'#DC2626',secondary:'#7C2D12',accent:'#FBBF24',bg:['#450A0A','#7C2D12'],boardBg:'rgba(153,27,27,0.3)',cellBg:'rgba(127,29,29,0.6)',cellBorder:'rgba(220,38,38,0.5)',seed:'#EF4444',text:'#FEE2E2',emoji:'🌅'},forest:{name:'Floresta',primary:'#059669',secondary:'#064E3B',accent:'#34D399',bg:['#022C22','#064E3B'],boardBg:'rgba(6,78,59,0.3)',cellBg:'rgba(6,95,70,0.6)',cellBorder:'rgba(5,150,105,0.5)',seed:'#10B981',text:'#D1FAE5',emoji:'🌳'},desert:{name:'Deserto',primary:'#CA8A04',secondary:'#713F12',accent:'#FDE047',bg:['#422006','#713F12'],boardBg:'rgba(113,63,18,0.3)',cellBg:'rgba(161,98,7,0.6)',cellBorder:'rgba(202,138,4,0.5)',seed:'#FACC15',text:'#FEF9C3',emoji:'🏜️'},ocean:{name:'Oceano',primary:'#0284C7',secondary:'#0C4A6E',accent:'#38BDF8',bg:['#082F49','#0C4A6E'],boardBg:'rgba(12,74,110,0.3)',cellBg:'rgba(7,89,133,0.6)',cellBorder:'rgba(2,132,199,0.5)',seed:'#0EA5E9',text:'#E0F2FE',emoji:'🌊'}};

function idxToRowCol(idx){return{row:Math.floor(idx/COLS),col:idx%COLS}}
function rowColToIdx(row,col){return row*COLS+col}
function nextIndex(idx,player){const{row,col}=idxToRowCol(idx);if(player===1){if(row===IDX.P1_DEF)return col<COLS-1?rowColToIdx(row,col+1):rowColToIdx(IDX.P1_ATK,COLS-1);if(row===IDX.P1_ATK)return col>0?rowColToIdx(row,col-1):rowColToIdx(IDX.P1_DEF,0)}else{if(row===IDX.P2_ATK)return col<COLS-1?rowColToIdx(row,col+1):rowColToIdx(IDX.P2_DEF,COLS-1);if(row===IDX.P2_DEF)return col>0?rowColToIdx(row,col-1):rowColToIdx(IDX.P2_ATK,0)}return idx}
function isPlayerSide(idx,player){const{row}=idxToRowCol(idx);return player===1?(row===IDX.P1_ATK||row===IDX.P1_DEF):(row===IDX.P2_ATK||row===IDX.P2_DEF)}
function isAttackRow(idx,player){const{row}=idxToRowCol(idx);return player===1?row===IDX.P1_ATK:row===IDX.P2_ATK}
function opponentAttackHouse(idx,player){const{col}=idxToRowCol(idx);return player===1?rowColToIdx(IDX.P2_ATK,col):rowColToIdx(IDX.P1_ATK,col)}
function opponentDefenseHouse(idx,player){const{col}=idxToRowCol(idx);return player===1?rowColToIdx(IDX.P2_DEF,col):rowColToIdx(IDX.P1_DEF,col)}
function createInitialBoard(){return Array(TOTAL).fill(INITIAL_SEEDS)}
function getPlayerIndices(player){const res=[];for(let i=0;i<TOTAL;i++)if(isPlayerSide(i,player))res.push(i);return res}
function countPlayerPieces(board,player){return getPlayerIndices(player).reduce((sum,idx)=>sum+board[idx],0)}
function isPhaseTwo(board){return board.every(c=>c<=1)}
function getValidMoves(board,player){const moves=[],indices=getPlayerIndices(player),phase2=isPhaseTwo(board);for(const idx of indices){if(board[idx]===0)continue;if(phase2){if(board[idx]===1)moves.push(idx)}else moves.push(idx)}return moves}

function calculateMoveSteps(board,idx,player){const steps=[];let b=[...board],seeds=b[idx];b[idx]=0;let current=idx;steps.push({type:'pickup',idx,count:seeds});let continueLoop=true;let safety=0;while(continueLoop&&safety<100){safety++;while(seeds>0){current=nextIndex(current,player);b[current]+=1;seeds-=1;steps.push({type:'drop',idx:current,board:[...b]})}if(b[current]>1){const pickedSeeds=b[current];b[current]=0;seeds=pickedSeeds;steps.push({type:'pickup',idx:current,count:seeds});continue}if(b[current]===1&&isAttackRow(current,player)){const oppAtk=opponentAttackHouse(current,player),oppDef=opponentDefenseHouse(current,player);if(b[oppAtk]>0){let totalCaptured=b[oppAtk]+b[oppDef];steps.push({type:'capture',idx:current,oppAtk,oppDef,count:totalCaptured});b[oppAtk]=0;b[oppDef]=0;b[current]=0;seeds=1+totalCaptured;continue}}continueLoop=false}steps.push({type:'complete',board:b});return steps}

function checkGameOver(board,currentPlayer){const p1Total=countPlayerPieces(board,1),p2Total=countPlayerPieces(board,2);if(p1Total===0)return{over:true,winner:2,reason:'Jogador 1 sem pecas'};if(p2Total===0)return{over:true,winner:1,reason:'Jogador 2 sem pecas'};const moves=getValidMoves(board,currentPlayer);if(moves.length===0){const opponent=currentPlayer===1?2:1;return{over:true,winner:opponent,reason:\`Jogador \${currentPlayer} sem jogadas validas\`}}return{over:false}}

function evaluateMove(board,idx,player){const steps=calculateMoveSteps(board,idx,player),finalBoard=steps[steps.length-1].board;let score=0;const opponent=player===1?2:1,oppBefore=countPlayerPieces(board,opponent),oppAfter=countPlayerPieces(finalBoard,opponent);score+=(oppBefore-oppAfter)*50;const ownAfter=countPlayerPieces(finalBoard,player);score+=ownAfter*2;return score}

function aiChooseMove(board,player){const moves=getValidMoves(board,player);if(moves.length===0)return null;let best=moves[0],bestScore=-Infinity;for(const idx of moves){const score=evaluateMove(board,idx,player);if(score>bestScore){bestScore=score;best=idx}}return best}

const{width:SCREEN_W,height:SCREEN_H}=Dimensions.get('window');
const CELL_SIZE=Math.min((SCREEN_W-24)/COLS-6,Math.max(68,(SCREEN_H-240)/ROWS-8));

function SeedDots({count,cellSize,theme}){if(count<=0)return null;if(count>12)return <View style={styles.seedStack}><Text style={[styles.seedCountLarge,{fontSize:cellSize*0.45,color:theme.accent}]}>{count}</Text><View style={[styles.seedDot,{position:'relative',marginTop:2,backgroundColor:theme.seed,width:cellSize*0.18,height:cellSize*0.18,borderRadius:cellSize*0.09}]}/></View>;const dots=[],radius=cellSize*0.28,cx=cellSize*0.42,cy=cellSize*0.42,dotSize=Math.max(10,cellSize*0.18);if(count===1)dots.push(<View key={0} style={[styles.seedDot,{top:cy-dotSize/2,left:cx-dotSize/2,backgroundColor:theme.seed,width:dotSize,height:dotSize,borderRadius:dotSize/2,shadowColor:theme.accent,shadowOffset:{width:0,height:2},shadowOpacity:0.6,shadowRadius:3,elevation:4}]}/>);else if(count===2){dots.push(<View key={0} style={[styles.seedDot,{top:cy-dotSize/2,left:cx-dotSize-2,backgroundColor:theme.seed,width:dotSize,height:dotSize,borderRadius:dotSize/2,shadowColor:theme.accent,shadowOffset:{width:0,height:2},shadowOpacity:0.6,shadowRadius:3,elevation:4}]}/>);dots.push(<View key={1} style={[styles.seedDot,{top:cy-dotSize/2,left:cx+2,backgroundColor:theme.seed,width:dotSize,height:dotSize,borderRadius:dotSize/2,shadowColor:theme.accent,shadowOffset:{width:0,height:2},shadowOpacity:0.6,shadowRadius:3,elevation:4}]}/>)}else{for(let i=0;i<count;i++){const angle=(i/count)*2*Math.PI-Math.PI/2,top=cy+radius*Math.sin(angle)-dotSize/2,left=cx+radius*Math.cos(angle)-dotSize/2;dots.push(<View key={i} style={[styles.seedDot,{top,left,backgroundColor:theme.seed,width:dotSize,height:dotSize,borderRadius:dotSize/2,shadowColor:theme.accent,shadowOffset:{width:0,height:2},shadowOpacity:0.5,shadowRadius:2,elevation:3}]}/>)}}return <View style={StyleSheet.absoluteFill}>{dots}</View>}

export default function App(){const[mode,setMode]=useState(null);const[board,setBoard]=useState(()=>createInitialBoard());const[currentPlayer,setCurrentPlayer]=useState(1);const[gameOver,setGameOver]=useState(null);const[animationSteps,setAnimationSteps]=useState([]);const[currentStepIndex,setCurrentStepIndex]=useState(-1);const[isAnimating,setIsAnimating]=useState(false);const[currentAnimIdx,setCurrentAnimIdx]=useState(null);const[message,setMessage]=useState('');const[showHelp,setShowHelp]=useState(false);const[showSettings,setShowSettings]=useState(false);const[selectedTheme,setSelectedTheme]=useState('savanna');const[animationSpeed,setAnimationSpeed]=useState(500);const[soundEnabled,setSoundEnabled]=useState(true);const[timerEnabled,setTimerEnabled]=useState(false);const[timerMinutes,setTimerMinutes]=useState(10);const[timeRemaining,setTimeRemaining]=useState(null);const[isPaused,setIsPaused]=useState(false);const msgTimer=useRef(null);const pulseAnim=useRef(new Animated.Value(1)).current;const audioContextRef=useRef(null);const timerIntervalRef=useRef(null);const theme=THEMES[selectedTheme];

useEffect(()=>{Animated.loop(Animated.sequence([Animated.timing(pulseAnim,{toValue:1.05,duration:1000,useNativeDriver:true}),Animated.timing(pulseAnim,{toValue:1,duration:1000,useNativeDriver:true})])).start()},[]);

const playDropSound=useCallback(()=>{if(!soundEnabled||Platform.OS!=='web')return;try{if(!audioContextRef.current)audioContextRef.current=new(window.AudioContext||window.webkitAudioContext)();const ctx=audioContextRef.current,osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=800;osc.type='sine';gain.gain.setValueAtTime(0.15,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(0.01,ctx.currentTime+0.08);osc.start(ctx.currentTime);osc.stop(ctx.currentTime+0.08)}catch(e){}},[soundEnabled]);

const showMessage=useCallback(text=>{if(msgTimer.current)clearTimeout(msgTimer.current);setMessage(text);msgTimer.current=setTimeout(()=>setMessage(''),2500)},[]);

const resetGame=useCallback(()=>{setBoard(createInitialBoard());setCurrentPlayer(1);setGameOver(null);setIsAnimating(false);setCurrentAnimIdx(null);setAnimationSteps([]);setCurrentStepIndex(-1);setMessage('');setTimeRemaining(null);setIsPaused(false);if(timerIntervalRef.current){clearInterval(timerIntervalRef.current);timerIntervalRef.current=null}},[]);

const executeMove=useCallback((idx,player)=>{if(gameOver||isAnimating)return;const moves=getValidMoves(board,player);if(!moves.includes(idx))return;const steps=calculateMoveSteps(board,idx,player);setAnimationSteps(steps);setCurrentStepIndex(0);setIsAnimating(true)},[board,gameOver,isAnimating]);

useEffect(()=>{if(!isAnimating||currentStepIndex<0||currentStepIndex>=animationSteps.length){if(isAnimating&&currentStepIndex>=animationSteps.length){const finalStep=animationSteps[animationSteps.length-1];setBoard(finalStep.board);setIsAnimating(false);setCurrentStepIndex(-1);setAnimationSteps([]);setCurrentAnimIdx(null);const nextPlayer=currentPlayer===1?2:1,over=checkGameOver(finalStep.board,nextPlayer);if(over.over)setGameOver(over);else setCurrentPlayer(nextPlayer)}return}const step=animationSteps[currentStepIndex];if(step.type==='drop'){playDropSound();setCurrentAnimIdx(step.idx);if(step.board)setBoard(step.board)}else if(step.type==='capture'){showMessage(\`🎯 Capturou \${step.count} peca(s)!\`);setCurrentAnimIdx(step.idx)}else if(step.type==='pickup')setCurrentAnimIdx(step.idx);const timer=setTimeout(()=>setCurrentStepIndex(prev=>prev+1),animationSpeed);return()=>clearTimeout(timer)},[isAnimating,currentStepIndex,animationSteps,animationSpeed,currentPlayer,playDropSound,showMessage]);

useEffect(()=>{if(mode==='single'&&currentPlayer===2&&!gameOver&&!isAnimating){const timer=setTimeout(()=>{const idx=aiChooseMove(board,2);if(idx!==null)executeMove(idx,2)},700);return()=>clearTimeout(timer)}},[mode,currentPlayer,board,gameOver,isAnimating,executeMove]);

useEffect(()=>{if(!mode||!timerEnabled||gameOver||isPaused){if(timerIntervalRef.current){clearInterval(timerIntervalRef.current);timerIntervalRef.current=null}return}if(timeRemaining===null&&mode){setTimeRemaining(timerMinutes*60)}timerIntervalRef.current=setInterval(()=>{setTimeRemaining(prev=>{if(prev===null)return null;if(prev<=1){clearInterval(timerIntervalRef.current);timerIntervalRef.current=null;const opponent=currentPlayer===1?2:1;setGameOver({over:true,winner:opponent,reason:'Tempo esgotado!'});return 0}return prev-1})},1000);return()=>{if(timerIntervalRef.current){clearInterval(timerIntervalRef.current);timerIntervalRef.current=null}}},[mode,timerEnabled,gameOver,isPaused,timerMinutes,timeRemaining,currentPlayer]);

const handleCellPress=idx=>{if(gameOver||isAnimating||isPaused)return;if(mode==='single'&&currentPlayer!==1)return;if(!isPlayerSide(idx,currentPlayer))return;executeMove(idx,currentPlayer)};

const validMoves=getValidMoves(board,currentPlayer),phase2=isPhaseTwo(board),p1Count=countPlayerPieces(board,1),p2Count=countPlayerPieces(board,2);

const renderCell=idx=>{const count=board[idx],isValid=validMoves.includes(idx),isHighlighted=currentAnimIdx===idx,{row}=idxToRowCol(idx),isAtk=row===IDX.P1_ATK||row===IDX.P2_ATK;return <TouchableOpacity key={idx} onPress={()=>handleCellPress(idx)} activeOpacity={isValid&&!isAnimating&&!gameOver?0.6:1} disabled={!isValid||isAnimating||gameOver} style={[styles.cell,{width:CELL_SIZE,height:CELL_SIZE,borderColor:isAtk?theme.primary:theme.cellBorder,backgroundColor:theme.cellBg,borderWidth:isAtk?3:2},isHighlighted&&{borderColor:theme.accent,borderWidth:4,transform:[{scale:1.1}],shadowColor:theme.accent,shadowOffset:{width:0,height:0},shadowOpacity:0.8,shadowRadius:10,elevation:10},isValid&&!isAnimating&&!gameOver&&{opacity:1,borderColor:theme.accent},count===0&&{opacity:0.5}]}><View style={[styles.cellInner,{backgroundColor:'rgba(0,0,0,0.3)'}]}/><SeedDots count={count} cellSize={CELL_SIZE} theme={theme}/>{isHighlighted&&<View style={styles.animIndicator}><Text style={{fontSize:CELL_SIZE*0.4}}>✋</Text></View>}{count===0&&!isHighlighted&&<Text style={[styles.cellIndex,{color:theme.text}]}>{idx+1}</Text>}</TouchableOpacity>};

